# Generated by Django 5.2.1 on 2025-05-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrations2', '0002_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('birthday_candy', 'Birthday Candy Theme'), ('birthday_green', 'Birthday Green Theme'), ('birthday_skyblue', 'Birthday Sky Blue Theme'), ('birthday_paradise', 'Birthday Paradise Theme'), ('birthday_peacock', 'Birthday Peacock Theme'), ('halsi_traditional', 'Halsi Traditional Theme'), ('halsi_floral', 'Halsi Floral Theme'), ('halsi_bright', 'Halsi Bright Theme'), ('bride_red', 'Bride Red Theme'), ('bride_pink', 'Bride Pink Theme'), ('bride_glam', 'Bride Glamorous Theme'), ('baby_blue', 'Baby Blue Theme'), ('baby_pink', 'Baby Pink Theme'), ('baby_yellow', 'Baby Yellow Theme'), ('nikka_red', 'Nikka Red Theme'), ('nikka_indoor', 'Nikka Indoor Theme'), ('nikka_outdoor', 'Nikka Outdoor Theme'), ('nikka_yellow', 'Nikka Yellow Theme'), ('candy', 'Candy Theme'), ('green', 'Green Theme'), ('skyblue', 'Sky Blue Theme'), ('paradise', 'Paradise Theme'), ('peacock', 'Peacock Theme')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
