# Generated by Django 5.2.1 on 2025-05-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebrations2', '0003_themebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themebooking',
            name='created_at',
        ),
    ]
