# Generated by Django 5.2.1 on 2025-05-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrations2', '0004_remove_themebooking_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themebooking',
            name='theme',
        ),
        migrations.AddField(
            model_name='themebooking',
            name='selected_theme',
            field=models.CharField(default='default_theme', max_length=100),
            preserve_default=False,
        ),
    ]
