# Generated by Django 5.2.1 on 2025-05-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrations2', '0006_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='themebooking',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='theme_bookings/'),
        ),
    ]
