# Generated by Django 5.2.1 on 2025-05-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrations2', '0007_themebooking_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='themebooking',
            name='image',
        ),
        migrations.AddField(
            model_name='theme',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='theme_images/'),
        ),
    ]
