# Generated by Django 5.2.1 on 2025-05-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrations2', '0008_remove_theme_slug_remove_themebooking_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='themes/'),
            preserve_default=False,
        ),
    ]
