# Generated by Django 5.2.1 on 2025-05-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrations2', '0009_theme_slug_alter_theme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='venues/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
